### ISSUE TITLE
Add "REPORT" as a new deletion reference

### ISSUE THREAD

**Issue by AliciaRaber** [SORMAS-Foundation/SORMAS-Project#11964] opened 2023-05-15 14:30 UTC
### Problem Description

Actually, the data reference date for automatic deletion of a case is by default set to CREATION, which - in case of cases is the entry 'casedata.creationdate'

There are several options as reference for automatic deletion:
https://github.com/SORMAS-Foundation/SORMAS-Project/wiki/Manual-&-Automatic-Deletion#deletion-references

According to an official decision, the reference date for the automatic deletion of a case has to be triggered by another reference date, which should be added to the deletion references and be called "REPORT"

~~The second reference date is 'casedata.reportdate' (DEMIS-Message triggers the report date during the processing of a lab/hospital message~~

### Proposed Change

~~Filing the field 'casedata.reportdate' as default for deletion reference instead of the actual entry 'creation'~~~
Add REPORT as another deletion reference that can be configured for entities.

### Added Value/Benefit

According to the decision of the state ministry of health and care it is necessary to change the new entry to ensure, that the automatic deletion of a case is performed after 10 years after reporting the case.

### Acceptance Criteria

- Case has been created with report date
- Case stayed for 10 years in case directory
- Case has not been deleted due to other reasons
- Automatic Case deletion is triggered by report date  

### Configuration Details
The value for the deletion reference of cases has to be modified to the new report.date when wanted

### Mockups

N/A

### Additional Information

N/A

**Comment by AliciaRaber** [comment] 2023-05-19 06:57
@MateStrysewske Please let me know if you need any feedback for this issue.

**Comment by adinaflorea9** [comment] 2023-06-11 07:56
Closing ticket as duplicate of (https://github.com/SORMAS-Foundation/SORMAS-Project/issues/12067) as discussed with @markusmann-vg .

**Closed by adinaflorea9** 2023-06-11 07:56 UTC
Labels: backend, needs-refinement, change, general
