### ISSUE TITLE
Error when trying to merge persons or delete the 'Addresses' entry created as the result of a merge

### ISSUE THREAD

**Issue by adinaflorea9** [SORMAS-Foundation/SORMAS-Project#12279] opened 2023-07-11 13:19 UTC
### Bug Description

On my local server, when trying to merge specific persons, or when trying to delete the entries from the 'Addresses' section of these persons, an error appears.

The persons have been merged before with multiple other persons. However, there are other persons in the DB that have also been merged multiple times, but the errors are not reproducible with them. **Some of the merged persons were initially created from 'Developer mode' in the 'Configuration' directory.**

The backup of my current DB state can not be attached in the ticket but will be provided for the developer that will look into the errors.

Two of the persons that the errors could be reproduces with:
![image](https://github.com/SORMAS-Foundation/SORMAS-Project/assets/96909231/5c1e2ff0-225b-446c-8135-5e6a4744758f)

### Reproduction Steps

I:
1. Logged in with an Admin+NatUser open the 'Persons' directory;
2. Enter the bulk edit mode;
3. Pick from the list of persons the two persons from the screenshot (bug description);
4. Click on 'Bulk actions' and select 'Merge';
5. In the 'Pick or merge person confirmation' pop-up click 'Proceed';
6. In the 'Pick or merge persons' pop-up select as remaining person THB3MS (discard TECAM7);
7. Click 'Merge';
8. In the 'Pick or merge person confirmation' pop-up click 'Confirm'.
Actual behavior: An error appears.

**Server logs at the time of the error:**
[Logs when trying to merge persons.txt](https://github.com/SORMAS-Foundation/SORMAS-Project/files/12015062/Logs.when.trying.to.merge.persons.txt)

II:
1. With an Admin+NatUser, open the person page of either one of the persons from the screenshot (bug description);
2. Navigate to the 'Addresses' section on the person page and open the entry visible in the list (the entry was created as the result of the merge);
11. Click 'Delete' on the addresses entry;
12. Click 'Save' on the person page.
Actual behavior: An error appears.

**Server logs at the time of the error:**
[Logs wehn trying to delete address.txt](https://github.com/SORMAS-Foundation/SORMAS-Project/files/12015027/Logs.wehn.trying.to.delete.address.txt)

### Expected Behavior

Both the person merge and the deletion of any entry in the 'Addresses' section should be successful.

### Affected Area(s)

Web app

### SORMAS Version

1.86.0

### Android version/Browser

Chrome

### User Role(s)

Admin+NatUser

### Server URL

local machine

**Comment by leventegal-she** [comment] 2023-08-29 10:29
I couldn't reproduce the issue. Both use cases have the same problem, there are some persons that have the same address instance.

I looked at the code and it seems that it could only happen when pushing persons or event participants via the rest api using the same uuid for the address field.

@adinaflorea9 could this be a possible scenario on your system?

**Comment by adinaflorea9** [comment] 2023-09-13 11:16
@leventegal-she yes, it could be specific, as there was an issue in the DB with persons that had the same location id, but that got issue got generated too by merging persons multiple times somehow.

**Comment by MateStrysewske** [comment] 2023-12-18 05:04
Since we got no reports of this issue from any other instance or system, I'll close it.

**Closed by MateStrysewske** 2023-12-18 05:04 UTC
Labels: bug, vaadin-app, needs-response, persons
