### ISSUE TITLE
Enabling of 'Enter bulk edit mode' should be consistent across directories 

### ISSUE THREAD

**Issue by adinaflorea9** [SORMAS-Foundation/SORMAS-Project#11881] opened 2023-04-20 11:12 UTC
### Problem Description

Currently, the enabling of the 'Bulk edit mode' across directories is not done in a consistent manner. The following screenshot depicts on what bulk edit is currently dependent in each directory:
![image](https://user-images.githubusercontent.com/96909231/233346906-b2b082c7-97c3-4451-80d3-bf5c1605c038.png)

### Proposed Change

Whether or not the bulk edit mode is enabled across directories should be made consistent and dependent on the 'Perform bulk operations in lists'. 

The access to bulk actions should continue to be based on the specific rights associated with the action (e.g. bulk action 'Delete' is currently displayed, but if the user does not have deletion rights for the respective entity a pop-up warning appears).

### Added Value/Benefit

Consistency in what concurs the display of bulk edit mode across the directories where it is implemented.

### Acceptance Criteria

**TBD**
- [ ] 'Enter bulk edit mode' is displayed in directories if the users have the right 'Perform bulk operations in lists';
- [ ] 'Enter bulk edit mode' being enabled should no longer be dependent on other edit rights, delete rights or merge rights;
- [ ] there are currently 5 different 'Perform bulk operations' user rights - should they all be kept and make them dependent on the major one of 'Perform bulk operations in lists' or should only the latter be kept?
- [ ] should the changes be added by default to the existing default user roles?

**Comment by MateStrysewske** [comment] 2023-12-18 05:26
Closed as a duplicate of #10994

**Closed by MateStrysewske** 2023-12-18 05:26 UTC
Labels: vaadin-app, change, general
