### ISSUE TITLE
Add bulk action progress window to "Archive" and "Dearchive" bulk actions [2]

### ISSUE THREAD

**Issue by MateStrysewske** [SORMAS-Foundation/SORMAS-Project#11463] opened 2023-02-08 12:21 UTC
### Problem Description

#11597 has introduced a progress window for the "Edit" bulk actions. This window needs to be applied to other bulk actions as well to be consistent and because it's a lot more user-friendly.

### Proposed Change

Add the progress window to the "Archive" and "Dearchive" bulk actions of all directories.

### Acceptance Criteria

- [x] All "Archive" and "Dearchive" bulk actions in all directories use the bulk action progress window introduced in #11597 when at least 40 entries are selected
- [x] The respective backend calls are done in batches of 20 entities when at least 40 entries are selected
- [x] The bulk action also works in the case detailed and contact detailed directories, which use different grids
- [x] Cancelling the action before it finishes leaves the selected entries that have not yet been processed still selected (as implemented in #11597)

**Comment by adinaflorea9** [comment] 2023-06-23 16:06
- [ ] III: For immunizations - when trying to archive an immunization from the immunization page the same error appears informing the user that they do not have the necessary rights (even though the user has the rights).
![image](https://github.com/SORMAS-Foundation/SORMAS-Project/assets/96909231/d09d4937-4b8b-4bde-82ec-73de3a90bbd0)

**Comment by MateStrysewske** [comment] 2023-06-27 11:01
@leventegal-she This pull request breaks the mobile app synchronization because you've added an `archived` field to the InfrastructureDto class, but ContinentDto, SubcontinentDto and AreaDto still have their own individual archived field. Please remove the archived field from those classes because they're ambiguous.

**Comment by adinaflorea9** [comment] 2023-06-28 12:17
I am reopening the ticket as with the latest SORMAS version individual cases can not be de-archived:
![image](https://github.com/SORMAS-Foundation/SORMAS-Project/assets/96909231/097499d9-4bb0-428a-b295-763352e90bef)

Logs from the local machine:
[case de-archive error.txt](https://github.com/SORMAS-Foundation/SORMAS-Project/files/11893936/case.de-archive.error.txt)

**Comment by carina29** [comment] 2023-06-30 09:02
I'm reopening this ticket because we had the following functionality before this ticket:
- when a user with archive rights archived/dearchived a single entity , a call was made to Survnet and as an outcome a report was downloaded (StatusProcessing field's value will be changed)
 - when a user with archive rights archived/dearchived entities in bulk mode , a call was made to Survnet and as an outcome a report was downloaded (StatusProcessing field's value will be changed)

The above mentioned functionality is not working anymore, the report is not downloaded.


A new ticket will be created for handling the exceptions which can occur ( exceptions from Survnet or any other exceptions).
Related to the above scenario, when Survnet is not connected to Sormas and a user with archive rights tries to archive/dearchive an entity/multiple entities => An exception should be thrown and the user should see a message that the archive/dearchive is not possible. This problem will be handled also in that new ticket. (Ticket number will be added here)

**Comment by carina29** [comment] 2023-06-30 12:19
I'll close this ticket because the above described problem is not caused by this ticket.
I'll create a new bug ticket.

Note: The bug is reproducible only for entities ( cases/events) which were at some point sent to Survnet, were soft deleted from Sormas ( which triggered a delete in Survnet) and were reshared again with Survnet.
There is a method which checks the already shared cases with Survnet (setArchiveInExternalSurveillanceToolForEntities), which contains a query to return the already shared Cases/Events with Survnet.
The query should check the last status (whether is "DELETED") but is checking if the "Deleted" status exists in the statuses of the case/event. I'll create a bug for this and I'll explain further details there.

**Comment by adinaflorea9** [comment] 2023-07-03 11:55
I am reopening the ticket due to the following: for a user that does not have archive rights (for example 'Archive cases' is missing) - the warning message that used to appear after clicking 'Yes' in the 'Confirm archiving' pop-up no longer appears. The user is simply directed to the 'Bulk operations progress' pop-up.

In the pop-up the progress bar does not load and the entities are not archived. Also, the user can not close the pop-up as when they click 'Cancel' and then 'Yes' in the 'Confirm action' pop-up they are simply redirected back to the 'Bulk operations progress' pop-up again.

Until the implementation of #12015 the warning message that used to appear after clicking 'Yes' in the 'Confirm archiving' pop-up  should continue to be displayed to stop the user from performing an action that they do not have rights for and to stop them being stuck in the bulk progress bar loop.

**Comment by leventegal-she** [comment] 2023-07-04 11:14
@adinaflorea9 This happens because the abstract implementation of running bulk operations, that we started to use for every bulk operation, lacks a proper error handling.

As we have decided to create a new issue for handling errors in a generic way I would close this ticket. The problem you find will be solved by that new issue in the next iteration.

**Comment by adinaflorea9** [comment] 2023-07-04 13:54
Closing the issue and moving it back to testing as the behavior described in the comment will be covered by an issue that will treat all exceptions/errors in a generic way.

**Closed by adinaflorea9** 2023-07-04 13:54 UTC
Labels: vaadin-app, design-usability, feature, general, ready

**Comment by adinaflorea9** [comment] 2023-07-05 06:20
Verified ticket on the local machine using the latest version of SORMAS from the development branch - 1.86.0-SNAPSHOT(c6ee5e2).
