### ISSUE TITLE
Creation of Sample Dashboard,  comments from testing

### ISSUE THREAD

**Issue by bernardsilenou** [SORMAS-Foundation/SORMAS-Project#11970] opened 2023-05-16 22:28 UTC
### Problem Description

https://github.com/hzi-braunschweig/SORMAS-Project/issues/11372 added a sample dashboard to sormas. This is a documentation of findings from testing and the corresponding issues, some of the points may need refinement. 

### Proposed Change

1. Add samples card to person view [10714](https://github.com/hzi-braunschweig/SORMAS-Project/issues/10714)
- In the sample card information, the result of the "Latest pathogen test"  is missing,  only the caption is shown even after many pathogen test results have been added to the sample.
- The design of the entities (ie name of attribute/indicator: enum or value) is not consistent, e.g  Type of test: Culture, rather than only  "Culture" (Optional). 

2. Create basic samples dashboard [8] #10721
- Filter for the district of the parent entity of the sample is missing.  @MateStrysewske  is there a reason why we can not add a district filter to all dashboards? For server instances that sormas is used at the district level and also in the usecase of this development, it would be good to add it. 
-  We can add and show the district by default even even for national users

3. Add bar graphs to sample dashboard [10744](https://github.com/hzi-braunschweig/SORMAS-Project/issues/10744)
- Legend colours are interchanged for the enums of the "final laboratory result", on the "final laboratory result chart" and "information box", eg pending and positive (see image attached). It may be good to also check the same for pathogen test

4. Add sample status map to sample dashboard [5] #10745
- Nodes for event participant samples are overwritten by case samples. It can be seen when filtering by the parent entity type, showing ep nodes only and later showing ep and case. We should overwrite using case nodes only if the ep or contact is converted to a case and the sample referenced both entities.
- The sum of counts for all samples is not always equal to the sum of the counts on the final laboratory results chart (when always short at least 7 entries checkbox is deactivated). 654 versus 652 when filtering samples in  2023 (done on May 15) on release-international.

### Added Value/Benefit

Quality improvement

### Acceptance Criteria

- [ ]  None for now since issues this is not a specific issue
- [ ]
- [ ]

### Mockups

![image](https://github.com/hzi-braunschweig/SORMAS-Project/assets/12996724/263568b7-391c-4cd5-bb1a-946bc90caac2)

### Additional Information

* server used in testing: https://release-international.sormas.netzlink.com/sormas-ui/
* version at the time of testing 1.83.1
* user role: admin + national user
* uuid of sample used in testing: RZPEFA-4EAP2D-UPNMUA-BKRCSNZM
* person associated: UWMTO3-UYW5K4-YAK4QP-HYV6SP3Q

**Comment by MateStrysewske** [comment] 2023-05-17 10:55
@bernardsilenou I can't really comprehend the issues regarding #10714; for me, the sample card shows all information (i.e. as soon as I add a pathogen test to the sample, the date and test type are filled when looking at the person through the person directory); concerning the second point, can you please attach a screenshot? I'm not really sure what you mean.

For the third point, I don't see a mismatch there; the arrow you've drawn points from pending to positive; as far as I can see, red is used for positive in both occasions, and orange is used for pending.

For the fourth point, I either don't fully get the situation or can't reproduce it. EP samples are showing for me, even when filtering by all types of sample associations. Please provide instructions on how to create data with which I can reproduce this issue. Concerning the second point, the question I'm asking myself is: Isn't the display of the bar chart totally wrong in the first place? There's almost no pending and a lot of positive final laboratory results displayed there, while in the information above, there are a lot more pending than positive samples. I think we might have somehow mixed up pathogen test results and final laboratory results here. What do you think?

I've added an issue for point 2:
https://github.com/hzi-braunschweig/SORMAS-Project/issues/11972

**Comment by bernardsilenou** [comment] 2023-05-18 02:15
@MateStrysewske 

> @bernardsilenou I can't really comprehend the issues regarding #10714; for me, the sample card shows all information (i.e. as soon as I add a pathogen test to the sample, the date and test type are filled when looking at the person through the person directory); concerning the second point, can you please attach a screenshot? I'm not really sure what you mean.

I added text to the screenshot, hope they can be seen. Point 1 is about the result of the pathogen test (the final lab result of sample works fine)
![image](https://github.com/hzi-braunschweig/SORMAS-Project/assets/12996724/4a24ddd7-a955-4711-aff5-960de0d1a80e)


> For the third point, I don't see a mismatch there; the arrow you've drawn points from pending to positive; as far as I can see, red is used for positive in both occasions, and orange is used for pending.
> 
 Sorry my text was not correct. The legend colours are dine but the values/placeholders/ counts are interchanged. For example, in dashboard attached, looking at final laboratory result info boxes, there are 524 samples with final lab result == pending, but you do not see them(orange bars) on the final lab chart. I manually sum the bars are realised that the counts for the red colours on chard correspond to pending (524).

If the counts and legend for the final lab result info boxes are correct, then the majority of the bins in the chat should be orange, followed by red, and just 2 green.

> For the fourth point, I either don't fully get the situation or can't reproduce it. EP samples are showing for me, even when filtering by all types of sample associations. Please provide instructions on how to create data with which I can reproduce this issue. Concerning the second point, the question I'm asking myself is: Isn't the display of the bar chart totally wrong in the first place? There's almost no pending and a lot of positive final laboratory results displayed there, while in the information above, there are a lot more pending than positive samples. I think we might have somehow mixed up pathogen test results and final laboratory results here. What do you think?
> 

This is what I meant, the display of the chart has issues,
If the counts are  fine, then we can map on the chart
ret to orange
green to red
orange to green

This screen capture is about the fourth point, observer what happens to the green and yellow icons.
https://github.com/hzi-braunschweig/SORMAS-Project/assets/12996724/a09d9e85-a8d8-4a0a-8e46-1247e926bead


> I've added an issue for point 2: #11972

**Comment by MateStrysewske** [comment] 2023-05-25 05:32
@bernardsilenou 
"Latest pathogen test:" is simply the heading, there's not supposed to be any text to the right of it. The result of the latest test will very likely resemble the final laboratory result of the sample anyway.

Concerning the bar chart, I'll discuss with Levi where the differences come from and will create an issue to resolve it.

I've also created an issue for the fourth point: #12000

**Comment by MateStrysewske** [comment] 2023-05-26 10:59
@bernardsilenou Levi explained in #12000 that the reason for this is that the samples in question are connected to multiple entities at the same time, and in that case, they are always shown as case samples as long as they're connected to a case. So I'd say this is expected behaviour.

**Comment by bernardsilenou** [comment] 2023-05-30 09:27
@MateStrysewske 
> @bernardsilenou "Latest pathogen test:" is simply the heading, there's not supposed to be any text to the right of it. 
The result of the latest test will very likely resemble the final laboratory result of the sample anyway.
> 
The design does not show that it's a heading. In the epidemiological data form, we used italics and non-bolded text to give more information (see image), what about using a similar format here?
![image](https://github.com/SORMAS-Foundation/SORMAS-Project/assets/12996724/740a4412-ade4-4caa-92ec-695ca5c59152). Renaming it to something like "_Attributes of latest pathogen test_" would improve clarity.


> Concerning the bar chart, I'll discuss with Levi where the differences come from and will create an issue to resolve it: #12001
> 
> I've also created an issue for the fourth point: #12000

**Comment by MateStrysewske** [comment] 2023-05-30 10:45
@bernardsilenou Agreed! Created another issue: https://github.com/SORMAS-Foundation/SORMAS-Project/issues/12013

I'll close this one then as I believe we've handled everything that has come up, correct? If I'm mistaken, feel free to reopen it again!

**Closed by MateStrysewske** 2023-05-30 10:45 UTC
Labels: change
