### ISSUE TITLE
[mSERS] Error appears when a Surveillance Officer tries to enter the mSERS directory 

### ISSUE THREAD

**Issue by mk-sgent** [SORMAS-Foundation/SORMAS-Project#12197] opened 2023-06-22 10:17 UTC
### Problem Description

After login as Surveillance Officer the error occurred when trying to access the mSERS directory.

### Reproduction Steps

1.Login as Surveillance Officer
2.Click on the mSERS button from navbar
Actual behavior: An error appears. 

<img width="967" alt="image" src="https://github.com/SORMAS-Foundation/SORMAS-Project/assets/97879405/8c9e9c2e-e5b3-407e-9b86-b56883e1aa21">

Logs from the local machine:
[Error msers surveillance officer.txt](https://github.com/SORMAS-Foundation/SORMAS-Project/files/11869259/Error.msers.surveillance.officer.txt)

### Expected Behavior

No error should appear when the Surveillance Officer user tries to access the mSERS directory.

### Affected Area(s)

Web app

### SORMAS Version

1.86.0-SNAPSHOT (958786b)

### Android version/Browser

Google Chrome

### User Role(s)

Surveillance Officer

### Server URL

https://test-auto.sormas.netzlink.com

**Comment by MateStrysewske** [comment] 2023-06-23 11:26
@mk-sgent Do you have access to logs on that server? Those would be pretty helpful here to identify the issue.

**Comment by adinaflorea9** [comment] 2023-06-23 11:36
@MateStrysewske and @mk-sgent I tried to reproduce this on test-auto, test-de2, local machine and the release instances and I do not get any error with the Surveillance Officer. I discussed this morning with @abrudanancuta and asked her to ask the automation team to maybe recheck their test and retry to reproduce the issue again.

**Comment by adinaflorea9** [comment] 2023-06-23 11:38
As a side note - it might be worth checking the user rights that are checked for the Surveillance Officer (make sure the default values match those of the user that you are using) bot for the user and the user role that the test is using specifically (since there were issues in the last weeks where teats were failing due to missing rights that were edited by someone) @mk-sgent

**Comment by mk-sgent** [comment] 2023-06-23 11:46
I think the issue is no valid anymore. I check it user Surveillance Office again and error is gone(no reproduce). Maybe it was user rights issue. Thanks for you  help @MateStrysewske @adinaflorea9

**Comment by mk-sgent** [comment] 2023-06-23 11:47
Maybe it was user rights issue. After two days error no reproduce anymore

**Comment by adinaflorea9** [comment] 2023-06-23 11:48
@mk-sgent  thank you for checking and closing the issue. I'll add the discard label. If there is any issue with the rights indeed or you need help to look into this let me or @abrudanancuta  know and I'll be happy to help too ;)

**Comment by mk-sgent** [comment] 2023-06-26 12:36
I reopen this ticket because the error was occurred in next step. Please back to Reproduction steps and analyze it again

**Comment by adinaflorea9** [comment] 2023-06-26 12:57
@mk-sgent @MateStrysewske already mentioned in ticket #12206 that both the error for the surveillance officer truing to access the mSERS directory and the error when a user tries to save a new aggregate report

**Comment by adinaflorea9** [comment] 2023-06-26 12:58
Reopening issue and adding the logs from the local machine.

**Comment by adinaflorea9** [comment] 2023-06-26 13:35
I got the logs from reproducing the error on my local machine and added them to the ticket. They should be enough, but if necessary when someone looks into fixing the issue I also have access to Jenkins and can get the log for the test-auto instance.

**Comment by MateStrysewske** [comment] 2023-06-28 12:19
Seems like this is the same issue as in #12182, I'll close this issue right here and document it in the other issue to make sure that we check whether a fix to it also resolves this problem.

**Closed by MateStrysewske** 2023-06-28 12:19 UTC
Labels: bug, vaadin-app, reporting, major

**Comment by adinaflorea9** [comment] 2023-06-28 12:52
Discarding ticket as per @MateStrysewske 's comment above.
