### ISSUE TITLE
Clicking on UUID of entities should open the edit form

### ISSUE THREAD

**Issue by bernardsilenou** [SORMAS-Foundation/SORMAS-Project#12616] opened 2023-10-08 14:58 UTC
### Bug Description

- On the directory for contacts and immunization, clicking on a specific uuid does not open the edit form. For example:
- Immunization: RBXYQQ-CXJAGQ does not open when clicked on the uuid on the immunization directory. However when clicking don't the person uuid, it opens the person edit form as expected. When clicking on the immunization uuid on the side info box of the parson form, it takes you back to the main directory and does not filter the specific immunisation.
- Contact: R2TDUJ-HDB65F  does not open also.

### Reproduction Steps

1. Connect to https://release-international.sormas.netzlink.com using admin + natiional user role
2. Go to the contact or immunisation directory and open the entities with uuid R2TDUJ-HDB65F or RBXYQQ-CXJAGQ by clicking on the uuid 

### Expected Behavior

- Clicking on all uuids should open the edit forms

### Affected Area(s)

Web app

### SORMAS Version

1.89.0

### Android version/Browser

Google chrome

### User Role(s)

admin + national user

### Server URL

https://release-international.sormas.netzlink.com/sormas-ui/

**Comment by bernardsilenou** [comment] 2023-10-08 15:42
The person with uuid XBXQH5-ISQ2VI-OJIILD-K5IC2KTI has a case (UKT3WI) that can be seen by a surveillance officer in the region (Berlin), district (SK Berlin Charlottenburg-Wilmersdorf) but this user can not open the case from the case directory. In addition, a user with an admin + national user role can not see the case on the case directory by searching UKT3WI

**Comment by MateStrysewske** [comment] 2023-10-09 07:19
@bernardsilenou I don't have issues opening contacts with the admin user. However, I could reproduce the immunization opening problem on the release-international server.

**Comment by MateStrysewske** [comment] 2023-10-10 06:54
The same problem also occurs with samples.

**Comment by MateStrysewske** [comment] 2023-10-10 06:56
There might be potentially useful logs in #12620, but the stack trace in them doesn't really match what I'd expect (because it's about saving pathogen tests, which doesn't happen when opening a sample).

**Comment by carina29** [comment] 2023-10-10 07:52
I've also tested this problem locally and on https://release-international.sormas.netzlink.com/. Locally everything works fine and can be opened with a click on the uuid.
On https://release-international.sormas.netzlink.com/ some of the immunization uuids can be opened other ones not ( I've marked with yellow from the first page the immunizations which can not be opened).
![image](https://github.com/SORMAS-Foundation/SORMAS-Project/assets/47103965/66229333-6472-4512-ba6e-3f8b08e6d942)

Related to the mentioned contact by Bernard, I could open it on release-international: 
![image](https://github.com/SORMAS-Foundation/SORMAS-Project/assets/47103965/83548450-b831-4f6f-9139-4ff1727bd9dd)

Related to the samples I could also reproduce for some of the uuids the problem ( I've marked with yellow the ones which can not be opened from the first page):
![image](https://github.com/SORMAS-Foundation/SORMAS-Project/assets/47103965/e4863b17-d173-4c09-a530-c4e4ab39e873)

I've also checked the logs on grafana for https://release-international.sormas.netzlink.com/ instance but there is nothing logged which could help us.
![image](https://github.com/SORMAS-Foundation/SORMAS-Project/assets/47103965/9904f770-d9e3-4eee-8b67-daa9c1e6aa35)

I'll try to find some link or similarities between the entities which can not be opened and I'll also check some other test instances.

**Comment by abrudanancuta** [comment] 2023-10-10 10:45
For the Sample the problem can be reproduced if you create a new sample for a Case or Contact, click the edit icon of the Sample. At this point in the logs there is thrown an error related to pathogen test.

**Comment by carina29** [comment] 2023-10-10 11:23
@abrudanancuta I'll try as you've described for the samples. Meanwhile I've created  for RBXYQQ covid immunization's user (person uuid VGYYAD-SP7M4Z-2RDT6W-HBOXKLHE) a new cholera immunization and now the the old immunization RBXYQQ which could not be opened can be opened and the new one TEVHYL created by me can not be opened. 
![image](https://github.com/SORMAS-Foundation/SORMAS-Project/assets/47103965/28245ee7-a246-421b-bc5c-2190b47cb6a8)

![image](https://github.com/SORMAS-Foundation/SORMAS-Project/assets/47103965/73d0ba7f-0d68-45f4-bfea-a2cdc4ceae58)


Since the newly created immunization by me some immunizations from my old comment can be opened and other ones no.
I also saw that in my above comment the immunizations which could not be opened were created by Automation Admin.
Right now I'm trying to recreate everything identically locally to see if I can reproduce there too.

**Comment by carina29** [comment] 2023-10-11 11:23
**Updates:**
I'll attach the logs appearing in Grafana (for some of the samples) if the logged in user tries to reproduce the problem as @abrudanancuta mentioned in one of the above comments: 
[LogsWhenEditingSample.txt](https://github.com/SORMAS-Foundation/SORMAS-Project/files/12868682/LogsWhenEditingSample.txt)

Yesterday I've also received for one of the a Sample created by a National user: 
[SampleEditingWithNationalUser.txt](https://github.com/SORMAS-Foundation/SORMAS-Project/files/12868704/SampleEditingWithNationalUser.txt)

Today we've had with @abrudanancuta a very long call in order to test everything. The mentioned problems only on release-international can be reproduced. 
- We've tried archiving/dearchiving the regions/districts ( example: Baden-Wurttemberg1234) which in some scenarios seemed to be assigned to a sample or case instead of the selected Baden-Wurttemberg - we could not find a 100% pattern why some cases/samples/immunizations can not be opened after some changes
- When an entity can not be opened from the Sormas UI also will not be returned in Postman requests used by @abrudanancuta 
- When new immunizations are added to a person Uuid => some of the old immunizations will work fine ( we'll be able to open the uuids) but we'll not be able to open the new immunizations in most scenarios

We've asked with @abrudanancuta for the some of the uuids ( we can not open right now these uuids) the data from DB from Frank in order to continue with the investigations:

case uuid -> XTXSLP-L75QPS-3VNJIK-7GUCSDOU
sample uuid -> QP7NJD-FGAQPR-UTTRUL-JJEYKMRM
immunization uuid -> TEVHYL-GFGIDT-SEVRRO-SLYLCB5Y

**Comment by abrudanancuta** [comment] 2023-10-13 12:04
Also this ticket was fixed by the reindex: https://github.com/SORMAS-Foundation/SORMAS-Project/issues/12627

**Closed** 2023-10-13 12:05 UTC
Labels: bug, vaadin-app, major, immunizations
