### ISSUE TITLE
Remove specific PERFORM_BULK_OPERATIONS user rights [1]

### ISSUE THREAD

**Issue by KristinaBorch** [SORMAS-Foundation/SORMAS-Project#10994] opened 2022-11-23 09:50 UTC
### Bug Description

The right PERFORM_BULK_OPERATIONS does not enable the bulk edit mode in case directory. It is only enabled when assigning the right PERFORM_BULK_OPERATIONS_CASE_SAMPLES. 

### Steps to Reproduce

1. Create a user role with the right PERFORM_BULK_OPERATIONS. Make sure the right PERFORM_BULK_OPERATIONS_CASE_SAMPLES is not assigned and rights for case and contact surveillance as well as tasks are assigned.
2. Create a user with the created user role from step 1
3. Login with user from step 2
4. Go to case directory and check for bulk edit mode (also check for contact and task)
5. Log back in with admin and assign right PERFORM_BULK_OPERATIONS_CASE_SAMPLES to user role from step 1
6. Log in with user from step 2
7. Check case directory for bulk edit mode

### Expected Behavior

Specific user rights for bulk operations are removed and access instead depends on the general PERFORM_BULK_OPERATIONS user right. This affects the following user rights:

- [x] PERFORM_BULK_OPERATIONS_CASE_SAMPLES
- [x] PERFORM_BULK_OPERATIONS_EVENT
- [x] PERFORM_BULK_OPERATIONS_EVENTPARTICIPANT
- [x] PERFORM_BULK_OPERATIONS_EXTERNAL_MESSAGES

In addition:

- [x] A database script has been added that grants all user roles that currently have one of those rights the general PERFORM_BULK_OPERATIONS right (if they don't already have it)

### System Details

* Device:
* SORMAS version: 1.76.7
* Android version/Browser:
* Server URL: 1401
* User Role:

**Comment by MateStrysewske** [comment] 2022-11-28 10:10
@KristinaBorch The PERFORM_BULK_OPERATIONS_CASE_SAMPLES user right was introduced in #3904; I think it was used to differentiate access to bulk actions in general from access to bulk actions for cases AND samples, but this design definitely has a lot of flaws. Anyway, this is not a bug, but actually "correct" behaviour right now, though I believe it makes sense to change this logic and get rid of this user right.

It was originally introduced because bulk actions weren't properly showing for admin surveillance supervisors, but we should find a different solution to tackle that problem. Please discuss with your colleagues whether this has priority; in the meantime, the issue can simply be fixed by giving the user roles that are supposed to have access to bulk actions in the case directory the PERFORM_BULK_OPERATIONS_CASE_SAMPLES user right.

**Comment by KristinaBorch** [comment] 2022-11-28 10:59
@MateStrysewske I just saw, that the description in the excel table with the explanations of standard users and user right might be misleading as it says the right PERFORM_BULK_OPERATIONS_CASE_SAMPE enables the bulk edit mode for case-samples. I habe highlighted the row in the attached file.  Could you change that with minimum effort? 
[SORMAS_Standardrollen_und_Benutzerrechte_deutsch.xlsx](https://github.com/hzi-braunschweig/SORMAS-Project/files/10102966/SORMAS_Standardrollen_und_Benutzerrechte_deutsch.xlsx)

**Comment by MateStrysewske** [comment] 2022-11-29 08:29
@KristinaBorch Fixed this (in English, German needs to come through Crowdin) in #11045 and will move this issue here out of the current sprint

**Comment by adinaflorea9** [comment] 2024-02-21 13:36
Verified ticket on the local machine using the latest version of SORMAS from the development branch - 1.95.0-SNAPSHOT(138ef7e).

The following ticket - #12015  deals with the bulk actions that are visible in the dropdowns of 'Bulk actions' even thought he users do not have rights for them.
 
The following ticket - #12997  deals with the fact that the button for 'Enter bulk edit mode' was disregarded by the current ticket in the Persons director, and the button appears there only if the user also has the right 'Merge persons' which is now currently inconsistent with the way we display the same button in all other directories.

**Comment by adinaflorea9** [comment] 2024-02-21 13:36
Verified ticket on the local machine using the latest version of SORMAS from the development branch - 1.95.0-SNAPSHOT(138ef7e).

The following ticket - #12015  deals with the bulk actions that are visible in the dropdowns of 'Bulk actions' even thought he users do not have rights for them.
 
The following ticket - #12997  deals with the fact that the button for 'Enter bulk edit mode' was disregarded by the current ticket in the Persons director, and the button appears there only if the user also has the right 'Merge persons' which is now currently inconsistent with the way we display the same button in all other directories.

**Closed by adinaflorea9** 2024-02-21 13:36 UTC
Labels: cases, backend, vaadin-app, change, ready
