### ISSUE TITLE
Demis - Cannot download lab message

### ISSUE THREAD

**Issue by abrudanancuta** [SORMAS-Foundation/SORMAS-Project#12871] opened 2024-01-09 13:49 UTC
### Bug Description

The problem of downloading a lab message appeared on 20th December for the version 1.93.0.
When user is trying to download a lab message a pop-up error appears and the file is not downloaded

Logs: 
[DemisDownloadError.txt](https://github.com/SORMAS-Foundation/SORMAS-Project/files/13874506/DemisDownloadError.txt)

### Reproduction Steps

1. As user go to Messages directory
2. Choose a lab message and click the download icon

### Expected Behavior

The lab message should be downloaded as a PDF file

### Affected Area(s)

Web app

### SORMAS Version

1.93.0

### Android version/Browser

-

### User Role(s)

NatUser + Admin

**Comment by MateStrysewske** [comment] 2024-01-10 08:02
Duplicate of #12846

**Closed by MateStrysewske** 2024-01-10 08:02 UTC
Labels: bug, laboratory, vaadin-app, critical
